spring:
  application:
    name: segment-event-example
## 断点暴露
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      access: read_only
## Apollo 配置中心
app.id: ${spring.application.name}
apollo:
  meta: https://apollo-configservice-wick-adtomic.pacvue.com
  cacheDir: /opt/data
  bootstrap:
    enabled: true
    eagerLoad.enabled: true
    namespaces: application
## segment 配置
segment.event:
  logger:
    amazon-sqs:
      region: "us-east-1"
      queueName: helium10-segment-dev
      aws-access-key:
      aws-secret-key:
  client:
    analytics:
      writeKey: cVRL2WXtsUB3W7qtaibcO1xYFDxDrIMp
server:
  port: 8082