spring:
  application:
    name: segment-event-example

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true

segment:
  event:
    logger:
      amazon-sqs:
        region: "us-east-1"
        queueName: helium10-segment-dev
        aws-access-key:
        aws-secret-key:
    client:
      analytics:
        writeKey:
server:
  port: 8082