spring:
  application:
    name: segment-event-example
    port: 9090

segment:
  event:
    clickhouse:
      store:
        data-source-properties:
          druid:
            driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
            url: jdbc:clickhouse://localhost:18123/default?clickhouse.jdbc.v2=true
            username: default
            password: default
            validationQuery: SELECT 1
            testWhileIdle: true
        table-name: SegmentEventLog
        enabled: true
    ## ??rabbit?????????
    rabbit:
      store:
        enabled: true
        uri: amqp://deploy:deploy@localhost:5672
        exchangeName: amq.direct
        routingKey: segment-event-example
        queueName: segment-event-example
    client:
      http:
        secret: "123123"
        base-url: "http://localhost:8080"
      file:
        path: "segment"
        file-name: "1.log"
        max-file-size-mb: 1
      socket:
        end-point: "/v1/import"
        host: "localhost"
        port: 9090
        timeout: 10000
        secret: "123123"
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true