spring:
  application:
    name: segment-event-example
    port: 9090

segment:
  event:
    logger:
      clazz: com.pacvue.segment.event.springboot.properties.impl.RabbitMQProperties
      properties:
        uri: amqp://deploy:deploy@localhost:5678
        exchangeName: amq.direct
        routingKey: segment-event-example2
        queueName: segment-event-example2
    store:
      distributed:
        clazz: com.pacvue.segment.event.springboot.properties.impl.RabbitMQProperties
        properties:
          uri: amqp://deploy:deploy@localhost:5678
          exchangeName: amq.direct
          routingKey: segment-event-example
          queueName: segment-event-example
    client:
      http:
        secret: "cVRL2WXtsUB3W7qtaibcO1xYFDxDrIMp"
        base-url: "http://localhost:8080"
      file:
        path: "segment"
        file-name: "1.log"
        max-file-size-mb: 1
      socket:
        end-point: "/v1/import"
        host: "localhost"
        port: 9090
      clickhouse:
        data-source-properties:
          druid:
            driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
            url: jdbc:clickhouse://localhost:18123/default?clickhouse.jdbc.v2=true
            username: default
            password: default
            validationQuery: SELECT 1
            testWhileIdle: true
        insertSql: |
          INSERT INTO SegmentEventLog (eventDate, hash, userId, type, message, result, operation, createdAt, eventTime)
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    secret: "cVRL2WXtsUB3W7qtaibcO1xYFDxDrIMp"
    app-id: segment-event-example
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true