spring:
  application:
    name: segment-event-example
    port: 9090

segment:
  event:
    store:
      distributed:
        clazz: com.pacvue.segment.event.springboot.properties.impl.RabbitMQRemoteStoreProperties
        properties:
          uri: amqp://deploy:deploy@localhost:5678
          exchangeName: amq.direct
          routingKey: segment-event-example
          queueName: segment-event-example
    logger:
      clazz: com.pacvue.segment.event.springboot.properties.impl.RabbitMQRemoteStoreProperties
      properties:
        uri: amqp://deploy:deploy@localhost:5678
        exchangeName: amq.direct
        routingKey: segment-event-example2
        queueName: segment-event-example2
    client:
      http:
        secret: "cVRL2WXtsUB3W7qtaibcO1xYFDxDrIMp"
        base-url: "http://localhost:8080"
      file:
        path: "segment"
        file-name: "1.log"
        max-file-size-mb: 1
      socket:
        end-point: "/v1/import"
        host: "localhost"
        port: 9090
    secret: "cVRL2WXtsUB3W7qtaibcO1xYFDxDrIMp"
    app-id: segment-event-example
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true