spring:
  application:
    name: segment-event-service
  datasource:
    url: jdbc:mysql://localhost:3306/your_database
    username: your_username
    password: your_password
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
server:
  servlet:
    context-path: /api
  context-path: /segment
  webflux:
    base-path: /api

