spring:
  application:
    name: segment-event-service
  datasource:
    url: jdbc:mysql://localhost:3306/your_database
    username: your_username
    password: your_password
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
  rabbitmq:
    host: localhost   # RabbitMQ 服务器地址（本地）
    port: 15672        # 默认端口
    username: deploy   # 默认用户
    password: deploy   # 默认密码
    virtual-host: "/" # 默认虚拟主机
server:
  servlet:
    context-path: /api
  context-path: /segment
  webflux:
    base-path: /api

cloud:
  aws:
    stack:
      name: MyStack
      region: us-west-2  # 您的 AWS 区域
    credentials:
      access-key: YOUR_AWS_ACCESS_KEY
      secret-key: YOUR_AWS_SECRET_KEY